### ISSUE TITLE
Enhance the scheduler UI

### ISSUE THREAD

**Issue by atallahhezbor** [thecourseforum/theCourseForum#164]
There are complaints about the scheduler not being intuitive. It could use some rearrangement and touch-ups to make it more clear and easy to use

**Comment by sneelz** [comment]
I think the idea of "generating" all possible schedules is kind of a new/different concept compared to what people normally think of when they think 'scheduler' altogether. It's pretty unclear that the current scheduler creates multiple schedules and that the blue bar is what "slides" through them.

**Comment by aw3as** [comment]
a rename to "generator" would be better. could also include a manual scheduler if people wish as well

**Comment by atallahhezbor** [comment]
The page title is still "Scheduler Generator" but I agree that it's unclear. I think more explicit wording will help as well as the "how-to" modal

**Comment by sneelz** [comment]
I like the idea of having a manual scheduler, because when I personally think of a course scheduler I think of a drag-and-drop. A manual scheduler and a generator could be in two separate tabs on the Scheduler page, but they would both use the same "Class Cart" sidebar that would function differently depending on the tab (drag-and-drop vs. select-and-generate). Idk if that's too confusing, though.

I also think there are too many buttons at the top of the scheduler and they should be consolidated a bit. Maybe a 'Save Schedule' and 'Manage Schedules' button, where clicking 'Manage Schedules' opens up a single modal where the user can load/delete/export a schedule.

**Comment by seanbspector** [comment]
I like the idea of generating schedules. I think it is innovative.

**Comment by aw3as** [comment]
@atallahhezbor is this closed by 3.0.1?

**Comment by atallahhezbor** [comment]
For the most part. I still feel like the modals for choosing sections could still use some work, as well as the display of the selected courses. Maybe @sneelz could give it another look?

But the parts of the scheduler that led to this issue being created have been fixed by 3.0.1
