### ISSUE TITLE
On the login page, put 'Please enter a valid UVa email.' in the correct place

### ISSUE THREAD

**Issue by cyt3ea** [thecourseforum/theCourseForum#280]
- Should be under sign up if user is signing up and does not provide a valid UVa email
- Should be under login if user is logging in and does not provide a valid UVa email

Bug that needs to be fixed:
![image](https://cloud.githubusercontent.com/assets/9666592/23837644/cba04cdc-0761-11e7-84f0-f035316123df.png)

**Comment by kienan** [comment]
I wouldn't necessarily call this a bug. For signing up, there should be an "invalid UVa email" alert. However, on login, you've already signed up with a valid UVa email, so there shouldn't be an alert of the same sort. Rather, there should just be a regular mismatched/incorrect login credentials error if you maybe put in your personal rather than school emial, I'd think. What do you think?

**Comment by cyt3ea** [comment]
I agree. Same thing happens for an invalid password. So I think what we should go for here are 'error' messages that indicate that the user signed up with a UVa email and his or her password is at least 8 characters.

![image](https://cloud.githubusercontent.com/assets/9666592/23928580/dd2a254a-08f6-11e7-9bdc-ae27f206569e.png)
